from odoo import api, models, _
from odoo.exceptions import UserError


class SaleOrder(models.Model):
    _inherit = "sale.order"

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            preserve_revision_name = (
                self.env.context.get("preserve_quotation_revision_name")
                and vals.get("name")
                and vals.get("revision_number", 0) > 0
            )
            if self.is_using_quotation_number(vals) and not preserve_revision_name:
                company = self.env["res.company"].browse(vals.get("company_id")) if vals.get(
                    "company_id") else self.env.company
                seq = self.env["ir.sequence"].with_company(company).next_by_code("sale.quotation")
                if not seq:
                    raise UserError(_("Missing sequence: sale.quotation for company %s") % company.display_name)
                vals["name"] = seq
        return super().create(vals_list)

    @api.model
    def is_using_quotation_number(self, vals):
        company = self.env["res.company"].browse(vals.get("company_id")) if vals.get("company_id") else self.env.company
        return not company.keep_name_so

    def copy(self, default=None):
        self.ensure_one()
        default = dict(default or {})
        default["origin"] = (self.origin + ", " if self.origin else "") + self.name
        return super().copy(default)

    def _prepare_confirmed_so_data(self):
        self.ensure_one()
        quo = (self.origin + ", " if self.origin else "") + self.name
        so_seq = self.env["ir.sequence"].with_company(self.company_id).next_by_code("sale.order")
        if not so_seq:
            raise UserError(_("Missing sequence: sale.order for company %s") % self.company_id.display_name)
        vals = {
            "origin": quo,
            "name": so_seq,
        }
        if "unrevisioned_name" in self._fields:
            vals["unrevisioned_name"] = so_seq
        if "revision_number" in self._fields:
            vals["revision_number"] = 0
        return vals

    def action_confirm(self):
        for order in self:
            # If config says use same numbering, do nothing special
            if order.company_id.keep_name_so:
                continue

            # Only convert quotations that were generated by quotation sequence
            # IMPORTANT: your prefix now starts with "PEC-", so don't check [:2] == "SQ"
            # Use the sequence code to detect: easiest is: "contains -SQ-" (based on your prefix)
            if not order.name or "-SQ-" not in order.name:
                continue

            if order.state not in ("draft", "sent"):
                continue

            so_vals = order._prepare_confirmed_so_data()
            order.write(so_vals)

        return super().action_confirm()

