from odoo import api, models, _
from odoo.exceptions import UserError


class SaleOrder(models.Model):
    _inherit = "sale.order"

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if self.is_using_quotation_number(vals):
                company = self.env["res.company"].browse(vals.get("company_id")) if vals.get(
                    "company_id") else self.env.company
                seq = self.env["ir.sequence"].with_company(company).next_by_code("sale.quotation")
                if not seq:
                    raise UserError(_("Missing sequence: sale.quotation for company %s") % company.display_name)
                vals["name"] = seq
        return super().create(vals_list)

    @api.model
    def is_using_quotation_number(self, vals):
        company = self.env["res.company"].browse(vals.get("company_id")) if vals.get("company_id") else self.env.company
        return not company.keep_name_so

    def copy(self, default=None):
        self.ensure_one()
        default = dict(default or {})
        default["origin"] = (self.origin + ", " if self.origin else "") + self.name
        return super().copy(default)

    def action_confirm(self):
        for order in self:
            # If config says use same numbering, do nothing special
            if order.company_id.keep_name_so:
                continue

            # Only convert quotations that were generated by quotation sequence
            # IMPORTANT: your prefix now starts with "PEC-", so don't check [:2] == "SQ"
            # Use the sequence code to detect: easiest is: "contains -SQ-" (based on your prefix)
            if not order.name or "-SQ-" not in order.name:
                continue

            if order.state not in ("draft", "sent"):
                continue

            quo = (order.origin + ", " if order.origin else "") + order.name

            so_seq = self.env["ir.sequence"].with_company(order.company_id).next_by_code("sale.order")
            if not so_seq:
                raise UserError(_("Missing sequence: sale.order for company %s") % order.company_id.display_name)

            order.write({"origin": quo, "name": so_seq})

        return super().action_confirm()
