# -*- coding: utf-8 -*-
{
    'name': 'pr_custom_purchase',
    'summary': 'Unified custom purchase requisition and portal workflow',
    'description': 'Merged module containing custom_pr_system and custom_user_portal functionality.',
    'author': 'My Company',
    'website': 'https://www.yourcompany.com',
    'category': 'Operations',
    'version': '17.0.1.0.0',
    'license': 'LGPL-3',
    'depends': ['base', 'portal', 'product', 'hr', 'mail', 'web', 'purchase', 'purchase_stock', 'stock', 'bus',
                'project', 'account', ],
    'data': [
        'security/custom_pr_groups.xml',
        'security/user_portal_groups.xml',
        'security/record_rules.xml',
        'security/ir.ui.menu.xml',
        'security/purchase_requisition_security.xml',
        'security/ir.model.access.csv',
        # 'security/user_portal_ir.model.access.csv',
        'views/custom_pr_views.xml',
        'views/budget_increase_request_views.xml',
        'views/inventory.xml',
        'views/remarks_popup.xml',
        'views/grn_report.xml',
        'views/remove_purchase_reports.xml',
        'views/custom_pr_templates.xml',
        'views/views.xml',
        # 'views/templates.xml',
        'views/portal_pr_form_template.xml',
        'report/custom_purchase_header_footer.xml',
        'report/custom_purchase_order_report.xml',
        'views/custom_purchase_rfq_views.xml',
        'views/cash_odoo_ui.xml',
        'views/pr_odoo_ui.xml',
        'views/project_view.xml',
        'views/expense_bucket_views.xml',
        'views/account_analytic_account_budget.xml',
        'views/pr_portal_view.xml',
        'views/rfq_vendor.xml',
        'views/purchase_order_inherit.xml',
        'views/rfq_comparison_wizard.xml',
        'views/res_users_supervisor.xml',
        'views/stock_picking_approval_views.xml',
        'data/custom_pr_ir_sequence_data.xml',
        'data/custom_purchase_rfq_sequence.xml',
        'data/budget_increase_sequence.xml',
        'data/user_portal_ir_sequence_data.xml',
        'data/mail_template.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'pr_custom_purchase/static/src/css/style.scss',
            'pr_custom_purchase/static/src/js/script.js',
            'pr_custom_purchase/static/src/xml/form.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}