{
    "name": "Petroraq: Sales Workflow",
    "summary": "Inquiry → Quotation → Manager Approval → MD Approval → Send to Client",
    "version": "17.0.1.0.1",
    "author": "Petroraq Engineering & Construction Co. Ltd.",
    "website": "https://petroraq.com",
    "category": "Sales",
    "license": "OEEL-1",
    "depends": [
        "sale",
        "mail",
        "account",
        "stock",
        "pr_work_order",
        "base_revision",
        "sale_order_revision",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/payment_terms.xml",
        "data/estimation_sequence.xml",
        # "data/sequence.xml",
        "views/sale_order_views.xml",
        "views/estimation_views.xml",
        "views/sale_order_tree_inherit_petroraq.xml",
        "views/reject_wizard_views.xml",
        "views/custom_format.xml",
        "views/pro_forma.xml",
        "views/sale_quotation_action_defaults.xml",
        "views/report_saleorder_petroraq_costing.xml",
        "views/stock_delivery_note_innherit.xml",
        "views/stock_backorder_confirmation_views.xml",
        "data/mail_template.xml",
        # "data/default_template.xml",

    ],
    "assets": {
        "web.assets_backend": [
            "petroraq_sale_workflow/static/src/scss/section_subtotals.scss",
            "petroraq_sale_workflow/static/src/css/sales_style.css",
            "petroraq_sale_workflow/static/src/xml/section_subtotals.xml",
        ],
    },
    "post_init_hook": "petroraq_sale_workflow_create_payment_terms",
    "application": False,
    "installable": True,
}