{
    "name": "PR Work Order",
    "version": "17.0.1.0.5",
    "category": "Projects",
    "summary": "Construction Work Orders integrated with Sales, Accounting, Inventory",
    "author": "Petroraq Engineering",
    "website": "",
    "license": "LGPL-3",
    "depends": [
        "sale_management",
        "project",
        "analytic",
        "account",
        "account_budget",
        "stock",
        "mail",
        "purchase",
        "pr_custom_purchase",
    ],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/work_order_views.xml",
        "views/job_costing_report_views.xml",

        "data/sequence.xml",
        "views/menu_views.xml",
        "views/sale_order_views.xml",
        "views/project_views.xml",
        "views/expense_bucket_views.xml",
        "views/account_move_views.xml",
        # "views/purchase_request_views.xml",
        "views/work_order_reject_wizard_view.xml",
        "views/work_order_pr_wizard_views.xml",

    ],
    "installable": True,
    "application": True,
}