{
    'name': 'Workspace Leave Management Dashboard',
    'version': '17.0.1.0.3',
    'summary': 'Advanced leave dashboard for all active employees',
    'description': 'Adds a single advanced leave dashboard under Employee Workspace with all-active-employee visibility.',
    'author': 'Aual Faisal',
    'website': 'https://petroraq.com',
    'category': 'Human Resources',
    'depends': ['de_hr_workspace', 'pr_hr_holidays', 'gs_hr_attendance_sheet', 'pr_hr_org_chart', 'report_xlsx'],
    'data': [
        'security/ir.model.access.csv',
        'views/leave_management_views.xml',
        'views/dashboard_export_wizard_views.xml',
        'report/period_absentees_reports.xml',
        'report/period_absentees_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'de_hr_workspace_leave_management/static/src/js/emp_org_chart.js',
            'de_hr_workspace_leave_management/static/src/js/time_off_emp_card.js',
            'de_hr_workspace_leave_management/static/src/js/leave_management_dashboard_action.js',
            'de_hr_workspace_leave_management/static/src/xml/approval_status_card_templates.xml',
            'de_hr_workspace_leave_management/static/src/xml/period_absentees_card_templates.xml',
            'de_hr_workspace_leave_management/static/src/xml/leave_management_dashboard_action_templates.xml',
            'de_hr_workspace_leave_management/static/src/xml/emp_org_chart_templates.xml',
            'de_hr_workspace_leave_management/static/src/xml/emp_department_card_templates.xml',
            'de_hr_workspace_leave_management/static/src/xml/time_off_emp_card_templates.xml',
            'de_hr_workspace_leave_management/static/src/css/hr_leave_dashboard.css',
            'hr_org_chart/static/src/fields/hr_org_chart.scss',
            'de_hr_workspace_leave_management/static/src/scss/time_off_dashboard.scss',
            'hr_holidays/static/src/dashboard/time_off_card.scss',
            'de_hr_workspace_leave_management/static/src/scss/calendar_renderer.scss',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}