{
    "name": "Petroraq: Customer Credit Limit",
    "summary": "Approved customer credit facilities and sale order credit exposure checks",
    "version": "17.0.1.0.0",
    "author": "Petroraq Engineering & Construction Co. Ltd.",
    "website": "https://petroraq.com",
    "category": "Sales",
    "license": "OEEL-1",
    "depends": [
        "sale_management",
        "account",
        "mail",
        "petroraq_sale_workflow",
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/ir_sequence_data.xml",
        "views/credit_limit_request_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
    ],
    "application": False,
    "installable": True,
}
