{
    "name": "PR Access Management",
    "version": "17.0.1.0.0",
    "summary": "Unified access management and advanced domain widget tools.",
    "category": "Tools",
    "author": "Mudassir",
    "depends": ["web", "account"],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "data/view_data.xml",
        "views/access_management_view.xml",
        "views/res_users_view.xml",
        "views/store_model_nodes_view.xml"
    ],
    "assets": {
        "web._assets_core": [
            "pr_acess_managment/static/src/tree_editor/tree_editor_autocomplete.js",
            "pr_acess_managment/static/src/tree_editor/tree_editor_operator_editor.js",
            "pr_acess_managment/static/src/tree_editor/tree_editor_value_editors.js",
            "pr_acess_managment/static/src/tree_editor/tree_editor.js",
            "pr_acess_managment/static/src/tree_editor/tree_editor.xml",
            "pr_acess_managment/static/src/domain_selector/domain_selector_operator_editor.js",
            "pr_acess_managment/static/src/domain_selector/domain_selector.js",
            "pr_acess_managment/static/src/domain_selector/domain_selector.xml",
            "pr_acess_managment/static/src/domain_selector_dialog/domain_selector_dialog.js",
            "pr_acess_managment/static/src/domain_selector_dialog/domain_selector_dialog.xml",
            "pr_acess_managment/static/src/dateSelectionBits/dateSelectionBits.js",
            "pr_acess_managment/static/src/dateSelectionBits/dateSelectionBits.xml",
            "pr_acess_managment/static/src/model_field_selector/model_field_selector.js",
            "pr_acess_managment/static/src/model_field_selector/model_field_selector.xml"
        ],
        "web.assets_backend": [
            "pr_acess_managment/static/src/js/action_menus.js",
            "pr_acess_managment/static/src/js/hide_chatter.js",
            "pr_acess_managment/static/src/js/cog_menu.js",
            "pr_acess_managment/static/src/js/form_controller.js",
            "pr_acess_managment/static/src/js/pivot_grp_menu.js",
            "pr_acess_managment/static/src/js/pivot_renderer.js",
            "pr_acess_managment/static/src/js/model_field_selector.js",
            "pr_acess_managment/static/src/js/search_bar_menu.js",
            "pr_acess_managment/static/src/domain/domain_field.js",
            "pr_acess_managment/static/src/domain/domain_field.xml",
            "pr_acess_managment/static/src/tree_editor/tree_editor_autocomplete.js",
            "pr_acess_managment/static/src/tree_editor/tree_editor_operator_editor.js",
            "pr_acess_managment/static/src/tree_editor/tree_editor_value_editors.js",
            "pr_acess_managment/static/src/tree_editor/tree_editor.js",
            "pr_acess_managment/static/src/tree_editor/tree_editor.xml",
            "pr_acess_managment/static/src/domain_selector/domain_selector_operator_editor.js",
            "pr_acess_managment/static/src/domain_selector/domain_selector.js",
            "pr_acess_managment/static/src/domain_selector/domain_selector.xml",
            "pr_acess_managment/static/src/domain_selector_dialog/domain_selector_dialog.js",
            "pr_acess_managment/static/src/domain_selector_dialog/domain_selector_dialog.xml",
            "pr_acess_managment/static/src/dateSelectionBits/dateSelectionBits.js",
            "pr_acess_managment/static/src/dateSelectionBits/dateSelectionBits.xml",
            "pr_acess_managment/static/src/model_field_selector/model_field_selector.js",
            "pr_acess_managment/static/src/model_field_selector/model_field_selector.xml"
        ]
    },
    "application": True,
    "installable": True,
    "auto_install": False,
}
